name: reusable-deploy

on:
  workflow_call:
    inputs:
      docker_image_tag:
        required: true
        type: string

    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      aws_assume_role_arn:
        required: true
      EKS_CLUSTER_NAME:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: EXtrai versão do POM
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Concatena nome completo da imagem
        id: full_tag
        run: |
          echo "tag=${{ inputs.docker_image_tag }}:${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker
        uses: docker/build-push-action@v6.15.0
        with:
          tags: ${{ steps.full_tag.outputs.tag }}
          context: .
          push: true

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_assume_role_arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region us-east-1

      - name: Altera versão do deployment.yaml
        run: |
          export IMAGE_TAG=${{ steps.full_tag.outputs.tag }}
          envsubst < k8s/deployment.yaml.template > k8s/deployment.yaml

      - name: Apply K8s
        run: kubectl apply -f k8s/
