name: pipeline-test

on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: true
        type: string
      sonar_organization:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Run Unit Tests
        run: mvn test

  code-analysis:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
