name: reusable-full-pipeline

on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: false
        type: string
      sonar_organization:
        required: false
        type: string
      docker_image_tag:
        required: false
        type: string
      enable_sonar:
        required: false
        type: boolean
        default: false
      enable_deploy:
        required: false
        type: boolean
        default: false

    secrets:
      SONAR_TOKEN:
        required: false
      DOCKERHUB_USER:
        required: false
      DOCKERHUB_TOKEN:
        required: false
      aws_assume_role_arn:
        required: false
      EKS_CLUSTER_NAME:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-test.yml
    with:
      enable_sonar: ${{ inputs.enable_sonar }}
      sonar_project_key: ${{ inputs.sonar_project_key }}
      sonar_organization: ${{ inputs.sonar_organization }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-deploy:
    if: ${{ inputs.enable_deploy }}
    needs: run-tests
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      docker_image_tag: ${{ inputs.docker_image_tag }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      aws_assume_role_arn: ${{ secrets.aws_assume_role_arn }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
